node_id: ""
server_address: "127.0.0.1:9443"
reconnect_backoff: 3s
send_queue_size: 4096
control_timeout: 10s
report:
  intervals:
    cpu_ultra_fast: 100ms
    cpu_medium: 100ms
    gpu_fast: 100ms
    memory: 100ms
    storage: 100ms
    network: 100ms
    process: 1s
  heartbeat: 2s
  batch_flush: 100ms
  max_per_batch: 6400
log:
  level: info
  format: console
tls:
  ca_file: "certs/ca.crt"
  cert_file: "certs/agent.crt"
  key_file: "certs/agent.key"
  server_name_override: "127.0.0.1"
